#!/bin/sh
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# NOTE: Heavily adjusted from the original tdb2.tdbloader

JVM_ARGS=${JVM_ARGS:--Xmx1200M}
exec java $JVM_ARGS -cp $FUSEKI_HOME/fuseki-server.jar tdb2.tdbloader $@
